### ISSUE TITLE
Compile isssue with cmake

### ISSUE THREAD

**Issue by gulmezmerve** [capablevms/cheri-examples#86]
Hello, 
We faced an issue when we compile it with CheriFreeBSD on Arm Morello Board. We got some strange error," invalid line type". Compile with `gmake``solves the problem.

**Comment by ltratt** [comment]
Can you give the precise sequence of commands that did and didn't work please? That way we can try and see if this is fixable, or is just due to the chaos of bmake/cmake/gmake!

**Comment by gulmezmerve** [comment]
![bild](https://github.com/capablevms/cheri-examples/assets/41786107/eb022bb3-e50d-4a22-808a-81904ed6d190)
I just did `git clone` and make!

**Comment by ltratt** [comment]
Right, I think this is a classic `bmake`/`gmake` thing :/ At the very least we should document this. I'll look into it shortly.

**Comment by 0152la** [comment]
It looks like you might be trying to run this on CheriBSD itself? If so, these examples are meant to be cross-compiled on another target, then copied over and ran.

**Comment by ltratt** [comment]
Although I haven't tried this, with the hybrid clang that's available on CheriBSD it might be possible to build on CheriBSD itself.

**Comment by gulmezmerve** [comment]
Thank you for all messages and interests! Appericated! 
I just want to put a small note if someone wants to try in my way.

**Comment by ltratt** [comment]
@gulmezmerve I forgot to say: thanks for the report (and please file other issues if/when you come across them!). https://github.com/capablevms/cheri-examples/pull/87 aims to help the next person!
